version: "3.9"

services:

  ms-auth:
    image: ghcr.io/ambintsoah/EC03_Redline_UrbanHub/ms-auth:latest
    ports:
      - "8000:8000"
    env_file:
      - ms-auth/.env
    networks:
      - urbanhub-net

  ms-user:
    image: ghcr.io/ambintsoah/EC03_Redline_UrbanHub/ms-user:latest
    ports:
      - "8001:8000"
    env_file:
      - ms-user/.env
    networks:
      - urbanhub-net

  ms-collecte-iot:
    image: ghcr.io/ambintsoah/EC03_Redline_UrbanHub/ms-collecte-iot:latest
    ports:
      - "8002:8000"
    env_file:
      - ms-collecte-iot/.env
    depends_on:
      - mqtt-broker
    networks:
      - urbanhub-net

  ms-analyse-trafic:
    image: ghcr.io/ambintsoah/EC03_Redline_UrbanHub/ms-analyse-trafic:latest
    ports:
      - "8003:8000"
    env_file:
      - ms-analyse-trafic/.env
    networks:
      - urbanhub-net

  ms-alerte:
    image: ghcr.io/ambintsoah/EC03_Redline_UrbanHub/ms-alerte:latest
    ports:
      - "8004:8000"
    env_file:
      - ms-alerte/.env
    networks:
      - urbanhub-net

  ms_validateur_capteur:
    image: ghcr.io/ambintsoah/EC03_Redline_UrbanHub/ms-alerte:latest
    ports:
      - "8006:8000"
    env_file:
      - ms_validateur_capteur/.env
    networks:
      - urbanhub-net

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    networks:
      - urbanhub-net

networks:
  urbanhub-net:
    driver: bridge